name: PR Name Checker

on:
  pull_request:
    types: [opened, edited]

jobs:
  pr-name-checker:
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    runs-on: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}

    steps:
      # Clone the repository to the runner
      - name: Checkout
        uses: actions/checkout@v6

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      # Install commitlint globally
      - name: Install dependencies
        run: |
          npm install @commitlint/config-conventional @commitlint/cli -g

      # Lint the PR title using commitlint
      - name: Lint PR title
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint
